# === Required or overridden ===
base_dir: "/datasets/sai/gencam"
pretrained_model_name_or_path: "cogvideox/CogVideoX-2b/models--THUDM--CogVideoX-2b/snapshots/1137dacfc2c9c012bed6a0793f4ecf2ca8e7ba01"  # Replace with actual path or env var expansion
video_root_dir: "FullDataset"
csv_path: "set-path-to-csv-file"  # Replace with actual CSV path

# === Data-related ===
stride_min: 1
stride_max: 3
hflip_p: 0.5
downscale_coef: 8
init_from_transformer: true
dataloader_num_workers: 2
val_split: "val"
dataset: "full"

# === Validation ===
num_inference_steps: 50
validation_prompt: ""
validation_video: "../resources/car.mp4:::../resources/ship.mp4"
validation_prompt_separator: ":::"
num_validation_videos: 1
validation_steps: 400
guidance_scale: 1.0
use_dynamic_cfg: false
just_validate: false
special_info: "just_one"

# === Training ===
seed: 42
mixed_precision: "bf16"
output_dir: "cogvideox-full"
height: 720
width: 1280
fps: 8
max_num_frames: 17
train_batch_size: 2
num_train_epochs: 200
max_train_steps: null
checkpointing_steps: 200
checkpoints_total_limit: null
gradient_accumulation_steps: 2
gradient_checkpointing: true
learning_rate: 0.0001
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 250
lr_num_cycles: 1
lr_power: 1.0
enable_slicing: true
enable_tiling: true

# === Optimizer ===
optimizer: "adamw"
use_8bit_adam: false
adam_beta1: 0.9
adam_beta2: 0.95
prodigy_beta3: null
prodigy_decouple: false
adam_weight_decay: 0.0001
adam_epsilon: 0.0000001
max_grad_norm: 1.0
prodigy_use_bias_correction: false
prodigy_safeguard_warmup: false

# === Logging & Reporting ===
tracker_name: "cogvideox-full"
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: "logs"
allow_tf32: true
report_to: null

# === Optional HuggingFace model variant ===
revision: null
variant: null
